import { Hero } from './hero';

export const HEROES: Hero[] = [
  { id: 11,
    name: 'Dr Nice',
    intelligence: 50,
    strength: 50,
    speed: 50,
    flight: false,
    img: '',
  },
  { id: 12,
    name: 'Ultor',
    intelligence: 90,
    strength: 90,
    speed: 70,
    flight: false,
    img: "url('../../assets/images/ultor.png')",
  },
  { id: 13,
    name: 'Crimson Chin',
    intelligence: 10,
    strength: 100,
    speed: 80,
    flight: true,
    img: '',
  },
  { id: 14,
    name: 'Ignis',
    intelligence: 80,
    strength: 70,
    speed: 100,
    flight: true,
    img: '',
  },
  { id: 15,
    name: 'Fluxtrol',
    intelligence: 10,
    strength: 10,
    speed: 10,
    flight: true,
    img: '',
  },
  { id: 16,
    name: 'Magneta',
    intelligence: 10,
    strength: 10,
    speed: 10,
    flight: true,
    img: '',
  },
  { id: 17,
    name: 'Dynama',
    intelligence: 10,
    strength: 10,
    speed: 10,
    flight: true,
    img: '',
  },
  { id: 18,
    name: 'Dr IQ',
    intelligence: 10,
    strength: 10,
    speed: 10,
    flight: true,
    img: '',
  },
  { id: 19,
    name: 'Magma',
    intelligence: 10,
    strength: 10,
    speed: 10,
    flight: true,
    img: '',
  },
  { id: 20,
    name: 'Tornado',
    intelligence: 10,
    strength: 10,
    speed: 10,
    flight: true,
    img: '',
  }
];
